name: C Compiler
on: [push]  # Τρέχει κάθε φορά που κάνεις push

jobs:
  build:
    runs-on: ubuntu-latest  # Linux environment
    steps:
      - uses: actions/checkout@v4  
      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc  
      - name: Compile C Code
        run: gcc main.c -o output_program  
      - name: Run the Program 
        run: ./output_program  
